[package]
name = "kcore"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
buddy_system_allocator = "*"
spin = "*"

[dependencies.lazy_static]
version = "*"
features = ["spin_no_std"]