[package]
name = "libsyscalls"
version = "0.1.0"
edition = "2021"

[features]
# Facilities for setting up system call handlers (used by the kernel)
handle = []
# (whether to include the example definitions)
examples = []

[dependencies]
